### ISSUE TITLE
support 'snap' as official installer

### ISSUE THREAD

**Issue by yodog** [caddyserver/dist#76]
i would like to suggest adding a `snap` container as a official install mode for Caddy.

**Comment by mholt** [comment]
More likely it would be added as a community-maintained distribution (first). Official distributions require a lot of commitment and maintenance, and usually the person to propose that is the one who ends up maintaining that. We could add it to the website, though, if it works. https://caddyserver.com/docs/install

**Comment by francislavoie** [comment]
Agreed, we could include it as "community maintained" at best. I'm personally not a fan of snaps for various reasons.

Your snap seems to use `caddy run --resume` by default -- most users use the Caddyfile instead for configuration.

You also have `confinement: strict` set which complicates serving static files.

**Comment by yodog** [comment]
hello everyone.

there is a reason to use `--resume` here: i want caddy to always [re]start the daemon with the last config used.

this is how i'm using my snap (local, not published on snapcraft.io yet):

1- snap install caddy --classic (gives access to filesystem)
2- netstat shows 127.0.0.1:2019 being used (no port 80 or 443, which is good)
3- now i can start my server with `caddy reload --config /path/to/Caddyfile` (if started with `run`, complains about port 2019 already being used)
4- if for whatever i have to restart the daemon or reboot the machine, it comes back using `/path/to/Caddyfile` (because my daemon have --resume)

below is my snapcraft.yml

```yaml
name: caddy-server
summary: Fast, multi-platform web server with automatic HTTPS.
description: |
    Caddy is a powerful, extensible platform to serve your sites, services, and
    apps, written in Go.
adopt-info: caddy

base: core20
confinement: classic
grade: devel

parts:
    xcaddy:
        build-snaps: [go]
        plugin: nil
        override-build: |
            go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
            mkdir -p $SNAPCRAFT_PART_INSTALL/bin
            cp -fv $(go env GOPATH)/bin/* $SNAPCRAFT_PART_INSTALL/bin/

    caddy:
        after: [xcaddy]
        build-packages: [build-essential, git]
        build-snaps: [go]
        plugin: nil
        override-build: |
            caddy_bin="$SNAPCRAFT_PART_INSTALL/bin/caddy"
            xcaddy build --output $caddy_bin
            caddy_version=$($caddy_bin version | awk '{print $1}')
            snap_version=$(date +%Y.%m.%d.%H%M)
            snapcraftctl set-version $snap_version

apps:
    caddy:
        command: bin/caddy
        plugs: [home, network-bind]
        environment:
            XDG_CONFIG_HOME: $SNAP_USER_COMMON
            XDG_DATA_HOME: $SNAP_USER_COMMON

    daemon:
        command: bin/caddy run --resume
        daemon: simple
        plugs: [home, network-bind]
        environment:
            XDG_CONFIG_HOME: $SNAP_COMMON
            XDG_DATA_HOME: $SNAP_COMMON
```
